-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 04, 2019 at 11:48 PM
-- Server version: 10.1.36-MariaDB
-- PHP Version: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mosque_description`
--
CREATE DATABASE IF NOT EXISTS `mosque_description` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `mosque_description`;

-- --------------------------------------------------------

--
-- Table structure for table `connection`
--

DROP TABLE IF EXISTS `connection`;
CREATE TABLE IF NOT EXISTS `connection` (
  `precedes` int(11) NOT NULL COMMENT '  First half of the primary key. Foreign key of the mosque that precedes the other in the relationship.',
  `succedes` int(11) NOT NULL COMMENT '  Second half of the primary key. Foreign key of the mosque that succeeded the other in the relationship.',
  PRIMARY KEY (`precedes`,`succedes`),
  KEY `HAS_CONNECTION_S` (`succedes`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `connection`
--

INSERT INTO `connection` (`precedes`, `succedes`) VALUES
	(31,7),
    (8,9),
    (9,10),
    (30,11),
    (64,12),
    (18,19),
    (80,20),
    (21,22),
    (44,26),
    (8,32),
    (70,34),
    (41,36),
    (31,39),
    (31,40),
    (31,41),
    (70,43),
    (31,44),
    (19,49),
    (8,52),
    (9,56),
    (8,57),
    (70,59),
    (80,62),
    (8,67),
    (17,68),
    (69,76),
    (30,82),
    (80,83),
    (84,85);


-- --------------------------------------------------------

--
-- Table structure for table `mosque`
--

DROP TABLE IF EXISTS `mosque`;


CREATE TABLE IF NOT EXISTS mosque (
  `id` int(11) NOT NULL COMMENT 'Primary key of the mosque.',
  `name` varchar(535) DEFAULT NULL COMMENT '  Name of the mosque.',
  `address` varchar(535) DEFAULT NULL COMMENT '  Street address of the mosque.',
  `phoneNum` varchar(535) DEFAULT NULL COMMENT '  Phone number of the mosque.',
  `website` varchar(535) DEFAULT NULL COMMENT '  URL address of the mosque.',
  `ethnicity` varchar(535) DEFAULT NULL COMMENT 'The primary ethnicity of the mosque.',
  `denomination` varchar(535) DEFAULT NULL COMMENT 'The denomination of the mosque.',
  `incorpDate` varchar(535) DEFAULT NULL COMMENT 'The date that the mosque was incorporated.',
  `openDate` varchar(535) DEFAULT NULL COMMENT 'The date that the mosque was opened.',
  `relocDate` varchar(535) DEFAULT NULL COMMENT '  The date that the mosque was relocated.',
  `dissDate` varchar(535) DEFAULT NULL COMMENT '  The date that the mosque was dissolved.',
  `fullDesc` longtext COMMENT '  The full description of the mosque.',
  `history` longtext COMMENT '  A description of the history of the mosque.',
  `albumId` varchar(535) DEFAULT NULL COMMENT 'The album id of the Flickr album containing pictures of the mosque.',
  `fBook` varchar(535) DEFAULT NULL COMMENT 'the url of the facebook page.', 
  `insta` varchar(535) DEFAULT NULL COMMENT 'the url of the instagram page.', 
  `lara` varchar(535) DEFAULT NULL COMMENT 'the url of the lara link', 
  `fMembers` varchar(535) DEFAULT NULL COMMENT 'the founding members of the location',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `mosque` (`id`, `name`, `address`, `phoneNum`, `website`, `ethnicity`, `denomination`, `incorpDate`,`openDate`, `relocDate`, `dissDate`, `fullDesc`, `history`, `albumId`, `fBook`, `insta`, `lara`, `fMembers` ) VALUES
  (1,'Abu-Bakr Al-Siddique Islamic Center','8904 St Aubin St Hamtramck, MI','(313) 875-4060','http://www.alsideeq.org/?fbclid=IwAR1YGykCW3mAGK-L4YnY1hIVwReZQdspySNJByUiCV3-80hL27yN-L4Lm8E','Yemeni','NULL','2012','2012','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/AbuBakrAlSiddiqueIslamicCenter/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800932143&SEARCH_TYPE=1','NULL'),
    (2,'Al-Islah Islamic Center (Jame Masjid) ','2733 Caniff Street Hamtramck, MI','(313) 365-9000','http://www.al-islah.us/','Bangladeshi','NULL','2000','2002','2016 - to 11301 Joseph Campau, Hamtramck','NULL','The Al-Islah Islamic Center is open daily for all prayers. The masjid occupies two floors of a building that was previously a medical clinic. It has a separate prayer space for women. The interior decoration is minimal, consisting mostly of a row of arches in the main prayer hall. Al-Islah currently sponsors a weekend Islamic school for children, where Arabic, Bangla, and Qur’an are taught. The congregation also runs a summer school. Adults meet weekly for tafsir (Qur’an study) on Sundays, and youth meetings are held once a month. Women attend the center most frequently for tafsir and special programming. While the mosque was founded by Bangladeshis, it is open to all Muslims. The administration has good relations with the local school board, with other mosques in the area, and with local churches and interfaith coalitions.','The Al-Islah Islamic Center was founded in 2000 by Bangladeshi immigrants, most of whom are followers of Allama Abdul Latif Chowdhury (Fultholi). The first Bangladeshi mosque in Hamtramck, Al-Islah was originally located in a small storefront on Joseph Campau and moved to its current home, a renovated medical clinic, in 2001. Al-Islah Islamic Center gained national media attention in 2004, when the congregation sought to broadcast their idhan (call to prayer) from a loudspeaker outside the mosque. The idhan has been broadcast publicly in Detroit since the 1970s, and in Dearborn since the 1980s, but many Hamtramck residents opposed this practice in their city. Al-Islah’s leadership found itself embroiled in an election year battle with the City Council. The matter was resolved in a special city-wide referendum, which Al-Islah and their supporters won handily. The mosque recently purchased a large historic building at the corner of Caniff and Joseph Campau which they plan to develop into a mosque and community center. The renovated larger space is expected to open in 2016. ','7.21576E+16','https://www.facebook.com/pages/Al-Islah-Islamic-Center-Inc/108098572564980','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800853519&SEARCH_TYPE=1','Abdul Motlib, Muhammad Ainul Huda, Mohammed Kibria'),
    (3,'Al-Rasool Community Center','8140 Greenfield Road Detroit, MI','NULL','NULL','Iraqi','NULL','2001','2001','NULL','NULL','NULL','This center is more of a community center than masjid.  Services are held during Ramadan and Ashura, but the masjid is not reliably open for daily or juma''a prayers.','7.21576E+16','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800834637&SEARCH_TYPE=1','NULL'),
    (4,'Al-Zahraa Islamic Center','15571 Joy Road Detroit, MI','(313) 633-1319','NULL','Iraqi','NULL','2012','2012','NULL','NULL','NULL','Located in the former home of the Islamic Center of America, Al-Zahraa opened in 2012 to provide religious services for the growing Iraqi Muslim population in the Detroit area.','NULL','https://www.facebook.com/alzahraaIslamiccenter','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800944430&SEARCH_TYPE=1','NULL'),
    (5,'Albanian Islamic Center','19775 Harper Avenue Harper Woods, MI','(313) 884-6676','https://www.aicod.org/','Albanian','NULL','1962','1963','NULL','NULL','The Albanian Islamic Center, built in Harper Woods in 1963, boasts a distinctive Balkan-style dome and minaret. With a prayer area, offices, large social hall, classrooms, and kitchen, the mosque serves an old Albanian American community (already well established in the 1940s) and new Muslim immigrants from Albania, Kosovo, Macedonia, and other Balkan countries. The center provides weekend religious instruction in Arabic, Albanian, and English along with other educational and service programs. The Albanian Islamic Center is open to Muslims from all ethnic backgrounds, but immigrants from Europe and their descendents form its core membership and predominate on its board. The mosque is unusual for its location in Detroit’s eastern suburbs.','Among the oldest mosques in metro Detroit, the Albanian Islamic Center was opened in 1963. The Center’s founder and first imam, Vehbi Ismail, came to Detroit in 1949 and established the Albanian American Moslem Society in the same year. The congregation met first at the International Institute of Detroit, moved to a former Armenian church on Hamilton Avenue, and shared prayer space briefly with the American Moslem Society in Dearborn while waiting for their current structure to be completed. Imam Shuajb Gerguri became acting head of the mosque in 1996 upon Imam Ismail’s retirement.','7.21576E+16','https://www.facebook.com/Albanianislamiccenter/','NULL','NULL','Vehbi Ismail'),
    (6,'Altaqwa Islamic Center','30069 Cherry Hill Rd Inkster, MI','(313) 999-6969','http://altaqwaislamiccenter.org/','Arab','NULL','7/21/2010','2010','NULL','NULL','All Muslims are welcome to this center where we can be brothers in the cause of Allah, following his commands, in which we can all unite and not divide. We extend our hand to any citizen in this country no matter what religion they follow and no matter what background they came from .. We take pride of our religion, but at the same time respect all others’ religions and beliefs. We are all humans. Moreover, we are all brothers in humanity. We all have descended from Adam, who was created from clay. We have named the center: (AI-Taqwa Islamic Center), to mean that we all should fear Allah and feel that he is always watching us.','NULL','NULL','https://www.facebook.com/Altaqwa-Islamic-Center-1457399507887985/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800926058&SEARCH_TYPE=1','NULL'),
    (7,'American Islamic Community Center','27205 Dequindre Road Madison Heights, MI','(248) 584-4100','http://www.aiccmi.com/about-aicc/','Lebanese American','NULL','2003','2003','NULL','NULL','NULL','This group began meeting in 2003 when they realized that a growing population of Muslims (roughly 250 families) were moving into the north eastern suburbs of Detroit and no masjids were nearby for them to worship in.  After meeting in one another''s homes, the group began renting space at St. George''s Antiochain Orthodox Church in Troy and in a local UAW hall as well.  They quickly moved to incorporate with the State of Michigan and to raise funds for the purchase of their center on Dequindre in Madison Heights.  Unlike their neighbor in Warren, IONA, this community experienced no difficulties with zoning boards or city administrators.  Their center opened in 2004 and includes a prayer space, classrooms, and a large meeting room that can be rented out for appropriate Islamic events and community weddings.  They have provided Saturday Islamic education classes for young people since 2006.   The congregation is predominantly Shia and Arab American.    ','7.21576E+16','https://www.facebook.com/aicc.madisonheightsmi/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800897939&SEARCH_TYPE=1','NULL'),
    (8,'American Moslem Society','9934 W. Vernor Highway Dearborn, MI','(313) 849-2147','http://amsdearborn.org/','Arab','NULL','1938','1938','NULL','NULL','NULL','This is the oldest existing mosque in Michigan.  Founded by several families from the Bekaa Valley in Lebanon, this institution anchored Detroit''s Muslim populations as a whole for several generations.  In the 1970''s, as new immigration changed the demographics of Dearborn and Muslim communities in Michigan, the mosque changed hands.  In 1981 it was reincorporated under this new leadership, led by Mohamed Shohatee and Abdo Alasry.  Today it remains open to all believers, but is manage by a predominantly Yemeni-American board of directors.  The building has been through many significant renovations.  The green dome pictured above was added in the mid 1950''s.  The group''s most recent expansion was completed in 2005, greatly increasing available space for congregational prayers, updating their classrooms, and adding a banquet and lecture hall. ','7.21576E+16','https://www.facebook.com/AMSDearborn/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800868275&SEARCH_TYPE=1','Families from the Bekaa Valley in Lebanon'),
    (9,'American Muslim Bekaa Center','6110 Chase Road Dearborn, MI','(313) 846-3498','NULL','Arab','NULL','1979','1979','NULL','NULL','NULL','Established in 1979 as the American Islamic League of Bekaa, the group changed their name in 1981 to the above and purchased and first renovated this facility in 1982.  It has undergone additional renovation since.  The congregation has grown so much in recent years that it helped establish a new facility, the Dearborn Muslim Center, in 2006/2007.  This new facility is better able to accommodate large congregations for Jumaa and holiday prayers.','7.21576E+16','https://www.facebook.com/pages/American-Moslem-Bekaa-Center/111727698864490','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800885111&SEARCH_TYPE=1','NULL'),
    (10,'American Muslim Center','21110 Outer Drive Dearborn, MI','(313) 565-9314','https://www.amcdearborn.net/','Arab','NULL','2001','2002','NULL','NULL','The American Muslim Center works for the welfare of the community. It establishes goodness and virtue. It eradicates evil and vice. It facilitates prosperity among all the people. It is a non-profit, charitable, educational, religious, social, cultural and scientific organization, educating the American society about Islam and promoting a positive relationship with all communities in the United States.','The story begins in 1993, when the core (existing Board of Trustees) had established the Foundation of Islamic Heritage as a non-profit organization serving the needs of Muslims in the greater Detroit area. In 2001, the same core established the American Muslim Center by purchasing a church in Dearborn, Michigan, renovated it, and maintained as a place of worship to God. The tired church is now a vibrant mosque and community center set right in the middle of a residential area. Its close proximity to a large area hospital and multiple Ford Motor Company corporate departments allows the employees of these firms to regularly attend the Friday (Jummah) prayers. Along with the five daily prayers, the center also has Sunday school for area children teaching them Qu’ran, Arabic and Islamic manners. For the adult community, there are lectures with guest speakers, and full family services with our resident Imam, Mohammad R. Mardini. ','7.21576E+16','https://www.facebook.com/American-Muslim-Center-135811563134044/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800888632&SEARCH_TYPE=1','NULL'),
    (11,'American Muslim Diversity Association','44760 RYAN RD Sterling Heights, MI','(586) 804-7130','http://www.amda.us/','Mixed','NULL','2006','2014','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/pages/American-Muslim-Diversity-Association/138232009646509','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800910107&SEARCH_TYPE=1','20 signatories'),
    (12,'American Yemeni Islamic Center','8564 Joseph Campau Hamtramck, MI','(313) 587-5248','NULL','Yemeni','NULL','2004','2004','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800907023&SEARCH_TYPE=1','NULL'),
    (13,'Anjumane Najmi/Masjid Al-Burhani','20959 Orchard Lake Rd Farmington Hills, MI','(248) 478-2001','http://www.detroitjamaat.online/','Mixed','NULL','6/9/1975','1975','NULL','NULL','We are the Dawoodi Bohra community of Detroit. As part of the Shia branch of Islam, the Dawoodi Bohras are a million-strong global faith with 140 families here in Detroit. We worship at our masjid, or mosque, Masjid ul Burhani, in the Farmington Hills suburb of Detroit.','The Detroit jamaat, or congregation, was established in 1971 by our then spiritual leader, the late Syedna Mohammed Burhanuddin. mankind. The Detroit jamaat, or congregation, was established in 1971 by our then spiritual leader, the late Syedna Mohammed Burhanuddin. In 1988 our jamaat (or community), Anjuman-e-Najmi, was honored to build the first Dawoodi Bohra masjid in the Western Hemisphere right here in Detroit. Our 130 families worship at the Burhani masjid, or mosque, in Farmington Hills. Our community continues to grow and flourish under the guidance of His Holiness, Dr. Syedna Mufaddal Saifuddin TUS, the 53rd Dai ul-Mutlaq or spiritual leader of the Bohra faith, who resides in India.','7.21576E+16','NULL','https://www.instagram.com/detroitjamaat/','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800867588&SEARCH_TYPE=1','NULL'),
    (14,'Association of Islamic Charitable Projects','5715 N. Inkster Road Garden City, MI','(734) 523-9940','http://aicpmi.org/index.html','Arab','NULL','12/2/1996','1996','NULL','NULL','The most important objective of the A.I.C.P. is to spread the correct knowledge of the Religion and teaching Muslims and non-Muslims about Islam by spreading the Islamic Obligatory Knowledge and supporting it with clear evidence.','The Association of Islamic Charitable Projects was founded in the 1930s by Ahmad al-Ajuz. According to Gary Gambill the AICP arrived in Lebanon in the 1950s, where he says "they blended Sunni and Shi''a theology with Sufi spiritualism into a doctrinal eclecticism that preached nonviolence and political quietism". The AICP remained without a leader until the 1980s when Abdullah al-Harari became the nominal head of the organization, and was taken over by Al-Ahbash in 1983.','7.21576E+16','https://www.facebook.com/AICP-Michigan-2225352137535558/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800826223&SEARCH_TYPE=1','NULL'),
    (15,'Baitul Ma''moor Sunni Islamic Center','11635 Conant Street Hamtramck, MI','(313) 445-2718','NULL','Bangladeshi ','NULL','1/13/2016','2016','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/BaitulMamoor11635/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=801999392&SEARCH_TYPE=1','NULL'),
    (16,'Baitul Muzaffar (Ahmadiyyah Movement of Michigan)','8218 Wyoming Street Detroit, MI','(313) 933-9850','NULL','South Asian','NULL','1979','1979','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','NULL','NULL'),
    (17,'Baitul-Islam Jame Masjid','7826 Klein Street Detroit, MI','(313) 922-6437','NULL','Bangladeshi ','NULL','1995','1995','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','NULL','NULL'),
    (18,'Bosnian American Islamic Center','3437 Caniff Street Hamtramck, MI','(313) 893-685','NULL','Bosnian','NULL','10/18/1995','1998','NULL','NULL','NULL','The Bosniak American Islamic Center began its work in 1998. The primary goal is to preserve Islam and Bosniak identity, culture and tradition.','7.21576E+16','https://www.facebook.com/BAIC-Detroit-117926154972231/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800815264&SEARCH_TYPE=1','NULL'),
    (19,'Bosnian Islamic Center','12426 Joseph Campau Hamtramck, MI','(313) 258-0726','NULL','Bosnian','NULL','6/21/2005','2005','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/Bosnian-Islamic-Center-Gazi-Husrevbeg-548579005239724/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800785954&SEARCH_TYPE=1','NULL'),
    (20,'Canton Islamic Center','5840 North Canton Center Road Canton, MI','(913) 575-8236','http://www.cicmi.org/','Mixed','NULL','2/10/2009','2009','NULL','NULL','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800919854&SEARCH_TYPE=1','NULL'),
    (21,'Dahira Taisiroul Hasir Touba','27500 Franklin Road Southfield, MI','NULL','NULL','African','NULL','1999','1999','2015','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/dahira.toubamichigan/timeline?lst=1016805770%3A100003321794947%3A1562096185','NULL','NULL','NULL'),
    (22,'Dar Al Salam Islamic Center','27758 Warren Road Westland , MI','(734) 338-2801','http://daiconline.org/','African','NULL','12/6/2005','2005','NULL','NULL','NULL','The journey of the establishment of Dar Al Salam Islamic Center (DAIC) began in December 2005. The goal was to establish a mosque in the city of Dearborn Heights, MI that would operate upon the noble Islamic principles of Ahlus-Sunnah wal Jama’ah. The Board of Trustees searched diligently for an adequate building for this mosque, and lack of sufficient funds called for an adjustment of plans. In November 2009, members of the community decided to rent a space in a shopping plaza in Garden City. For the next five year, this space would serve as a musallah for the community. In June 2014, the Board of Trustees felt a strong need for establishing a full-fledged mosque, and so they began the search for an appropriate building and location. They identified a very suitable and appropriate sized building in the city of Westland. During Ramadan of that year, a fundraising Iftar was organized. All praise is due to Allah, the fundraising was successful and the building was purchased under a land contract. After a couple of months of renovation, the new mosque opened its doors on December 1, 2014. The building costs have since been paid off, and several new renovations have been completed. Among them was a complete rebuilding of the bathrooms for men and women, external brick lining of the building, brand new HVAC units, new high efficiency windows, and a 100% coverage security camera system. Today, the Dar Al Salam Islamic Center (DAIC) establishes the five daily prayers, the Friday prayers, and the two Eid prayers.','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800905194&SEARCH_TYPE=1','NULL'),
    (23,'Daru Salam Center (Life for Relief and Development)','17300 W. 10 Mile Road Southfield, MI','(800) 827-3543','http://www.lifeusa.org/site/PageServer','African','NULL','5/4/1994','1992','NULL','NULL','Life for Relief and Development is a non-profit humanitarian charity founded in 1992 by concerned Arab and Muslim American professionals in response to the humanitarian crises that developed in Iraq as a result of the 1991 Gulf War.','This group has grown into a large and well respected Islamic charity, with offices around the world.  Their Southfield office includes a small prayer area intended for the use of their staff, but other Muslims who live and work in the area also use them for Jumaa prayers.','7.21576E+16','https://www.facebook.com/Life4ReliefUSA/','https://www.instagram.com/life4relief/?hl=en','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=801069194&SEARCH_TYPE=1','NULL'),
    (24,'Darul Uloom Michigan (Madani Muslim Community Service)','2446 E Twelve Mile Rd, Warren, MI','(313) 445-8827','http://www.darululoommi.org/','South Asian','NULL','2014','2015','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/DUMICHIGAN/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800942977&SEARCH_TYPE=1','Mohammed Taj Uddin'),
    (25,'First Albanian Bektashi Monastery','21749 Northline Road Taylor, MI','(734) 287-3646','http://www.bektashi.net/bio-babarexheb.html','Albanian','NULL','1954','1954','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','NULL','NULL'),
    (26,'Imam Ali Islamic Center','16003 W. Warren Avenue Detroit, MI','NULL','https://www.imam-us.org/location/imam-ali-mosque-detroit/','Iraqi','NULL','2002','2002','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','NULL','NULL'),
    (27,'Imam Jaafar Al-Sadeq Center','19111 W Warren Ave  Detroit, MI','(313) 406-2438','NULL','Iraqi','NULL','2013','2013','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/imamalsadeq/?__tn__=%2Cd%2CP-R&eid=ARC1raCkAZNxMLmYS1GxY7zcRh5QE-rilQ9Zv4-j7InQgFwD1PKHKyS8A3uF3uMpjyG1E1bJNOVZLc7R','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800942921&SEARCH_TYPE=1','Ali Moussawi, Dean Hydar Haddad, Jaafar Hameed'),
    (28,'Iraqi American Islamic Center','7219 Normille  Dearborn, MI','(248) 757-7000','NULL','Iraqi','NULL','6/3/2016','2016','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/Iraqi-American-islamic-Center-1917601628498635/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=802001202&SEARCH_TYPE=1','NULL'),
    (29,'Islamic American University Masjid','23725 Northwestern Highway Southfield, MI','(248) 213-0001','http://www.islamicau.org/','Mixed','NULL','2005','2005','NULL','NULL','NULL','The IAU Masjid includes a mosque and a lecture hall, which serve the neighboring communities of Southfield, Farmington Hills, Bloomfield, and northwest Detroit.  The 3,000 sq. foot masjid held its first congregational prayer in December 2005.  The masjid was established by the Muslim American Society and is connected to campus of the Islamic University of America, an on-line training program for Muslim laity and clergy.  The Masjid hosts a variety of services which include Friday sermons and prayers, Tafsir classes (an explanation of the meaning of the Qur''an) classes, lectures, and charitable works.  The Masjid and lecture hall are also used by local non profit organizations such as the Council of Islamic Organization of Michigan, the Islamic Shura Council of Michigan, the Muslim American Society Detroit Chapter, al-Nisa Foundation, and the Muslim American Society Youth Department.','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=802000879&SEARCH_TYPE=1','NULL'),
    (30,'Islamic Association of Greater Detroit','879 W. Auburn Road Rochester Hills, MI','(248) 852-5657','www.iagd.net','South Asian','NULL','1978','NULL','NULL','NULL','NULL','As the northern suburbs grew, so did the number of Muslims seeking a sense of community. Groups gathered in private homes for Islamic study and prayers. The existing Masjids were too far away to attend regularly and the need for a local Masjid was imperative. In April 1978, with thirty member families, the Islamic Association of Greater Detroit was established as a non-profit organization. The expanded facility opened in November, 2001. The expansion provided critically needed space in the prayer area and an enlarged dining hall, gymnasium, formal classrooms, conference room, library, professional kitchen and other amenities. A few years after the 2001 expansion , with the continuous growth of the community, the expanded facilities seemed too small to accommodate the fresh needs. IAGD had to spread its Sunday School education classes over Saturday and Sunday. Furthermore, daytime school was also established and the needs and demands for education continue to grow. Additional land was acquired and plans are currently being drawn to further expand the facilities.','7.21576E+16','https://www.facebook.com/iagd.net/?__tn__=kC-R&eid=ARAN8iIi3c4xHO-_cQm9zrYLMXV_-VzaFhw5adqvxkFNvgeqAjVp-YzJXb9oVcpFGvwwCp8UChuE9R-u&hc_ref=ARTnz4x0bI3j33pv6x1iy_1uNMbqa-nejwBowPa4kbM2qnZ-OIg7CsrpqT_Gyz6Zqrk&fref=nf&__xts__[0]=68.ARA4Tei-eyfk0Ctlx5gaMP4QsKkoTHb8g8BEmjDpJBAZ06RGnCx8hq2oEozOBgPkYWrgeckEqPF2McAn4hFAjJe9nItyNkmJQB3U5lJA3O5Kpd-RdFdk_4tU5QlAqqKNm98g7UyX-zdn0r9cpZvAYE2GGkayjkqTqwC6c5M1As77-d0wQtkyyGzk7qLdq980ghlgLICvIG3zVK1t9kcE07FmvgcQ7GWN2m9y6ehNGvIicaZ-wvmGbWIApen1C5EeuOtTBW53QlyV6pr8FKLNaH-sM-ny6xuFbDkVtPmP5mYIvVQF9htMBONOBXBM7IUkBpI6NqbcNc-TTlcEiLxt8hctog','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800792319&SEARCH_TYPE=1','NULL'),
    (31,'Islamic Center of America','19500 Ford Road Dearborn, MI','(313) 593-0000','http://www.icofa.com/','Arab','NULL','1950''s','1950','NULL','NULL','The Islamic Center’s new mosque, at 120,000 sq. ft., is grand in comparison to its earlier facility (17,000 sq.ft.), yet both structures are distinctive for the large spaces they set aside for religious and social events. The new mosque includes a vast meeting hall that can be divided into several smaller rooms, an industrial kitchen, a spacious prayer room with a high, calligraphy-decorated dome, a generously proportioned mezzanine for women, offices, meeting rooms, a library, and archival space set aside to document the community’s history in America. Led by Imam Hassan Qazwini, the Islamic Center offers a wide range of religious, educational, and public programs. It is frequently host to interfaith tour groups and visiting dignitaries from around the world. With a congregation of over 3,000 members, the center has long been one of Detroit’s most vibrant and influential Muslim institutions. A calendar of events, lectures by Imam Qazwini, prayer times, programs, and photographs of the new mosque are available at www.icofa.com.','NULL','7.21576E+16','NULL','NULL','NULL','NULL'),
    (32,'Islamic Center of Detroit','14350 Tireman Street Detroit, MI','(313) 584-4143','http://www.icd-center.org','Arab','NULL','1998','1998','NULL','NULL','NULL','Initially, the organization continued to meet in homes and also rented space in Larson Middle School for lectures and community dinners. In just one year, vigorous fund-raising accomplished purchasing a three-acre parcel of land. The property included a small blue house and garage which were immediately put to use as a home for the community. By 1982, the plans and continued fund-raising made the construction of the IAGD masjid a reality.','7.21576E+16','https://www.facebook.com/IcdIslamicCenterOfDetroit/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800842551&SEARCH_TYPE=1','NULL'),
    (33,'Islamic Center of Hamtramck','11345 Joseph Campau Detroit, MI','(740) 746-3336','http://icoh.us/','Arab','NULL','1/22/2008','2007','NULL','NULL','NULL','This facility is more of a Quran school than masjid.  It is located in the same block with Masjid Al-Falah and al-Iklas Training Academy.','7.21576E+16','https://www.facebook.com/IslamicCOH/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800915510&SEARCH_TYPE=1','NULL'),
    (34,'Islamic Center of North Detroit (Masjid al-Falah)','12500 McDougall Street Hamtramck, MI','(313) 368-5308','http://masjidalfalah.org/','South Asian','NULL','1989','1990','2006','NULL','NULL','This growing and dynamic mosque was established in 1989, first occupying a small house in Hamtramck.  As the group grew, they then moved into a former health clinic on McDougall along the border between Hamtramck and Detroit.  In 2007 they began renovating the former catholic parish they now occupy, which can accommodate up to 2,000 worshipers and is home to Al-Iklas Training Academy, the area''s oldest Islamic parochial school.  Established by South Asian Muslims, the community provides a link between urban and suburban Muslims and the school, in particular, has a culturally diverse population of students.  The masjid is working hard to expand their services into the areas of youth programming, health care, and end of  life services.','7.21576E+16','https://www.facebook.com/ICNDMasjid/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800857656&SEARCH_TYPE=1','Ali Suleiman Ali, Hafiz Azizur Rahman, Abdul Hoque, Sofrul Laskar, Nizam Ahmed, Syed Anwar Miah, Mohammed Halim, Mohammed Quayoum, Qurban Sani Choudhury, Mohammed Rahman, Muhammed Nasser'),
    (35,'Islamic Center of Southfield','23435 Berg Road Southfield, MI','(248) 864-8106','https://www.tawheedcs.org/','Mixed','NULL','2012','2012','NULL','NULL','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800932471&SEARCH_TYPE=1','Shaikh Gauhar Ahmed, Frijuckic Murat, Khondker Haque'),
    (36,'Islamic Council of America','6941 Schaefer Road Dearborn, MI','(313) 584-4488','NULL','Arab','NULL','1989','1989','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/icofalive/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800859870&SEARCH_TYPE=1','NULL'),
    (37,'Islamic Cultural Association','32220 Franklin Road Franklin, MI','(248) 988-7517','http://www.ica-mi.org','Syrian','NULL','1984','1984','NULL','NULL','Since its inception, the ICA has held various school and family functions for the occasions that matter most to its members—such as Ramadan and Eid—as well as exciting activities for the whole family. It has also prided itself in offering weekly Islamic and educational lectures and maintaining a youth program that has been going strong for years, Alhamdulilah. The ICA hopes to continue to expand by offering more services that the community can benefit from.','The Islamic Cultural Association was founded by a group of families who hoped to establish an Islamic community that modeled their beliefs and values. In 1987, the community purchased the Franklin Building and moved to its present location. Two years later, it established the prestigious Huda School which has flourished over the years, alhamdulilah. The ICA created a weekend Arabic School, Dar-al Huda.','NULL','https://www.facebook.com/MichiganICA/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800865112&SEARCH_TYPE=1','NULL'),
    (38,'Islamic Cultural Institute','30115 Greater Mack Avenue St. Clair Shores, MI','(586) 293-5752','http://icionline.org/','Egyptian','NULL','1993','1993','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/groups/184333858273584/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800793518&SEARCH_TYPE=1','NULL'),
    (39,'Islamic House of Wisdom','22575 Ann Arbor Trail Dearborn Heights, MI','(313) 584-2570','www.islamichouseofwisdom.com','Arab','NULL','1995','1995','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/IslamicHouseofWisdom/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800815136&SEARCH_TYPE=1','NULL'),
    (40,'Islamic Institute of America','26305 Ford Road Dearborn Heights, MI','(313) 432-8722','http://www.iiofa.org/','Lebanese','NULL','5/25/2011','2015','NULL','NULL','The IIA is a not-for- profit 501(c)3 charitable organization with tax exemption status. Centered around education, the Institute promotes the teachings of Islam following the traditions of the Ahlulbayt. Events catering to both English-speaking and Arabic-speaking audiences include Friday prayer, Youth programs, Sunday breakfast, Quranic Tafsir classes, Ramadan programs, Ashura programs, and Islamic retreats, among many more. Over the years, the IIA has empowered leaders dedicated to servitude and community engagement to provide these programs to audiences of all ages.','The Islamic Institute of America, Founded in 2015, is located in Dearborn Heights, Michigan, USA. Founded by Imam Sayed Hassan Qazwini and funded by community donations, the institute is made up of over 1000 families with diverse ethnicities','NULL','https://www.facebook.com/theiiofa/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800929801&SEARCH_TYPE=1','NULL'),
    (41,'Islamic Institute of Knowledge','6345 Schaefer Rd. Dearborn, MI','(313) 584-2570','http://www.iiokonline.org/','Lebanese','NULL','1982','1982','1998','NULL','NULL','The Institute moved to its current location in 1998 after extensively renovating this former bowling alley as a mosque, library and community center.  The facility''s large Husseniyya is used for lectures, funerals, commemorations, and for "Islamic weddings."  The mosque is located next to Riverside Academy, a charter school with an emphasis on Arabic-language instruction and gender segregated classrooms.  (See Islamic Institute of Knowledge, Historic, for more information about this mosque''s history.)','7.21576E+16','https://www.facebook.com/Islamic-Institute-of-Knowledge-IIOK-340193375997381/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800792880&SEARCH_TYPE=1','NULL'),
    (42,'Islamic Organization of North America','28654 Ryan Road Warren, MI','(586) 558-6900','http://www.ionaonline.org','Mixed','NULL','5/4/2005','2005','NULL','NULL','We are on a journey to transform ourselves and our surrounding communities to righteous God-fearing people who collectively strive for the highest moral standard and constantly seek forgiveness from our Lord to earn His pleasure. We seek His compassion and mercy in this life and in the Hereafter. We rejuvenate our soul through internal struggle and spiritual exercise in worship of our Creator Allah (SWT). The strength of our belief in Allah (SWT) gives us the courage to establish good and forbid evil, thus promoting a system of justice for all mankind. Our slogan is “Repentance, Revitalization of Faith, Renewal of Covenant.”','IONA is established to assist the Muslims in North America to implement Islamic obligations and to invite the non-Muslims to Islam.','7.21576E+16','https://www.facebook.com/ionaonline/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=801070871&SEARCH_TYPE=1','NULL'),
    (43,'Jamia Islamia Darul-Uloom Detroit','5679 Caniff Ave Hamtramck, MI','(313) 891-3256','http://www.darululoomdetroit.net/','Bangladeshi','NULL','1998','1998','NULL','NULL','The institution is now a three-story, fifteen thousand square feet building with 11 teachers and over 80 students from all over the Detroit-Metropolitan area. Our goal is to instill in each student the love and understanding of Allah (S.W.T.), His Prophet (S.A.W.), the Deen of Islam, and to develop a positive Muslim identity as well as commitment to religion, family, and community. Our institution provides Alim Course Studies, an experienced Hifz Course and a new organized Maktab Program for both male and female students. Additionally, we offer secular studies for grades K-12. ','Jamia Islamia Darul Uloom Detroit was founded in 1998. From its inception it has served as a cornerstone in revolutionizing the identity of the Muslims in the Metro Detroit area by providing sound Islamic Knowledge. The institution started off as a small house with a few teachers and students.','NULL','https://www.facebook.com/jamia.darululoomdetroit','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800855772&SEARCH_TYPE=1','Abdul Matin, Abdul Hakim Azad, Mohammed Atik Miah, Abdul Mumin, Abdul Quayum, Haris Ali'),
    (44,'Karbala Islamic Education Center','15332 W. Warren Avenue Dearborn, MI','(248) 525-0785','NULL','Iraqi','NULL','1995','1995','NULL','NULL','The Karbala Education Center is located along a busy commercial strip in the heart of a thriving Middle Eastern community in Dearborn, a middle-class suburb of Detroit. The Karbala Islamic Education Center, housed in a former nightclub that had been damaged by fire, contains approximately 10,000 square feet of space that have been converted into a prayer room, offices, an all-purpose meeting room, an audio-visual room, kitchen, and an area to hold a weekend school for children.It is run by Imam Husham Al-Husainy and other community members.','The institution started off as a small house with a few teachers and students. Founded in 1995 by Imam Husham Al-Hussainy, a Michigan resident for over 35 years and community leader. KIEC was the first Iraqi Islamic Center in Michigan.','7.21576E+16','https://www.facebook.com/Karbalaa-Islamic-Educational-Center-120334721315825/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=802116030&SEARCH_TYPE=1','Imam Husham Al-Hussainy'),
    (45,'Masjid al Ihsan (Ideal Islamic Center)','2721 Holbrook Hamtramck, MI','(313) 872-6000','http://www.darulihsanmi.org/index.html','Bangladeshi','NULL','2011','2011','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/IdealIslamicCenter/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800930312&SEARCH_TYPE=1','Fakrul Islam, Mohammad Salim Uddin, Abdul Matin Ullah, Abdul W. Chowdhury, Azizur Rahman, Afzal Chowdhury'),
    (46,'Masjid al-Fatheh (Islamic Center of Warren)','24703 Ryan Road Warren, MI','(313) 598-6417','http://www.icwweb.org/','Bangladeshi','NULL','2012','2012','NULL','NULL','Islamic Center of Warren founded to assist Muslims to become a better Muslim through educational, religious, socio-economic, and cultural services to develop moral community citizen. And to promote interfaith activities to build bridges of understanding among diverse faiths.','NULL','NULL','https://www.facebook.com/islamiccenterofwarren/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800934218&SEARCH_TYPE=1','Mohammed Basith, Faisal Ahmed, Mohibur Rahman Khan, Mujib-Ur Rahman, Manmur Rahman, Anamul Haque, Muhibul Hassan Chowdhury, Abdul Hakiem Khalisadar, Mohammed Huda'),
    (47,'Masjid al-Fatiha','2844 4th Street Detroit, MI','NULL','NULL','African American','NULL','1990','1990','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','NULL','Abdul Aleem Abdullah, Khaleel Deaab, Meer Raaur Ameen Abdullah, M. Rasheed Askew'),
    (48,'Masjid al-Fatimah (Hope Center)','12818 Joseph Campau Detroit, MI','(313) 444-4554','http://www.masjidfatimah.org/','Bangladeshi','NULL','2003','2014','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/MasjidFatimah/?__tn__=%2Cd%2CP-R&eid=ARD-od3h3RwAS6U9f3stCbwgVx67W53SfuNrisZbiIJGeOR7OtDJxSQurpvFoKiY-uo0G_ii6rvt_J_D','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800895494&SEARCH_TYPE=1','Akm Rahman'),
    (49,'Masjid al-Furqaan','27643 Schoenherr Rd Warren, MI','(248) 495-8742','NULL','Bosnian','NULL','2014','2015','NULL','NULL','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800942412&SEARCH_TYPE=1','Sejad Melkic, Senid Tica, Anes Halimic'),
    (50,'Masjid al-Furqān','4981 Cabot St Detroit, MI','(313) 584-4464','http://www.quran-institute.org/masjid-furqan','Yemeni','NULL','6/10/2015','2012','2018','NULL','NULL','NULL','NULL','https://www.facebook.com/Al-furqan-Masjid-%D9%85%D8%B3%D8%AC%D8%AF-%D8%A7%D9%84%D9%81%D8%B1%D9%82%D8%A7%D9%86-420371428698672/?eid=ARAmdVRRnROjvE2kGRQFKaM7VoHSK61cZofGIfLvID2Wl4yV98jgygg6pnsT97h852t386Z0g0YV9Z9x','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800941318&SEARCH_TYPE=1','NULL'),
    (51,'Masjid al-Haqq','4118 Joy Road Detroit, MI','NULL','NULL','African American','NULL','2009','1983','2009','NULL','Our mission is to develop, support, and promote an Islamic way of life. Our goal is to strengthen the community of believers and to bring about a bond between the Muslims and Non-Muslims alike. Jum"ah Prayer, every Friday 2:15pm. Soup Kitchen every Sunday at 2:30pm.','The mosque is currently under the leadership of….','7.21576E+16','https://www.facebook.com/masjidalhaqq4118/?rf=211413952318929','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=802232226&SEARCH_TYPE=1','NULL'),
    (52,'Masjid Al-Huda/Al-Huda Islamic Association ','5838 Lawndale Street Detroit, MI ','(313) 581-7555','https://www.alhudamosque.org/contact','Yemeni','NULL','7/24/1998','Sept. 1998','Dec. 2019','NULL','NULL','The al-Hoda Islamic Center was inistially launched as a neighborhood prayer space for the growing Yemeni community in SW Detroit. The congregation continued to worship woth the American MOslem Society for holidays and Fridya prayers. But as their community grew and moved further East along Wyoming and Lonyo, the group eventually decided to build a congregational mosque of their own. They will move to their new location  at 8835 W. Warren Ave., Dearborn. ','7.21576E+16','https://www.facebook.com/pages/Alhuda-Islamic-Association/203095996699645','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800855161&SEARCH_TYPE=1','NULL'),
    (53,'Masjid Al-Nur','318 Pilgrim Street Highland Park, MI','(313) 867-9428','NULL','African American','NULL','1989','1989','NULL','NULL','NULL','Offshoot of Masjid As-Salaam.','NULL','https://www.facebook.com/pages/Masjid-Nur/366608040042839','NULL','NULL','NULL'),
    (54,'Masjid Al-Nur (Jumaa)','MI','NULL','NULL','African American','NULL','1989','2003','NULL','NULL','NULL','Masjid Al-Nur uses this facility at the corner of Midland and Hamilton for congregational prayers, taraweeh, holidays, and other large gatherings.  Daily prayers are held at their facility on Pilgrim Street.','NULL','NULL','NULL','NULL','NULL'),
    (55,'Masjid al-Rahma','7520 Bingham St. Dearborn, MI','NULL','NULL','Senegalese','NULL','2011','2014','NULL','NULL','NULL','NULL','NULL','NULL','NULL','NULL','Amadou Diallo, Mamadou S. Diallo, Abraham Bah, Andoul Diallo'),
    (56,'Masjid Al-Salam (Dearborn Community Center)','3900 Schaefer Road Dearborn, MI','NULL','NULL','Mixed','NULL','2006','2010','NULL','NULL','NULL','Purchased in 2006 as the Dearborn Community Center, Masjid Al-Salam opened its doors in January 2010 as a spacious new mosque with an active weekend Arabic school, a gym and cafeteria.  The facility also houses the Dar Al-Arqam School.  This masjid represents a new step taken in the history of the American Muslim Bekaa Center (est. 1978), which itself spun off from the American Moslem Society (est. 1938) after that mosque voted in new leadership in the 1970''s.  In this case, the Bekaa Center has been so overwhelmed by Friday and holiday crowds that the City of Dearborn ordered the congregation to cease hosting jumaa and holiday prayers in violation of local zoning regulations.  The congregation simply outgrew their facility.  This new masjid serves a diverse, but majority Yemeni American, congregation.  Friday sermons are held in both Arabic (1st prayer) and English (2nd prayer).  See for images and a news story.','7.21577E+16','https://www.facebook.com/MasjidAlSalam/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800910341&SEARCH_TYPE=1','Adnan al-Kadri, Mohamad Bahalman'),
    (57,'Masjid al-Tawheed','18624 W. Warren Avenue Detroit, MI','(313) 271-0731','http://www.masjidtawheed.org/wordpress/','Mixed','NULL','1995','1995','NULL','NULL','Masjid Al-Tawheed is established on the principles of Ahlus Sunnah wa Al Jamaah. The guidance derived from the correct understanding of The Quran (The Book of Allah) and The Sunnah (The way of His Messenger sallallahu alayhi wa sallam) upon the understanding of the pious predecessors. We stick to this Manhaj (Methodology) to the best of our capabilities and we take knowledge from the noble scholars of this Methodology. Sheikh Abdul Azeez Ibn Baaz, Sheikh Nasser ud Din Al Albani, Sheikh Saleh Ibn Utahimeen, Sheikh Muqbil Al Hadee and from this time Sheikh Rabee Al Madhkhali, Sheikh Saleh Al Fauzan, Sheikh Abdul Mohsin Al Abaad and their likes.','Masjid Al-Tawheed was established in Detroit, Michigan in 1995. Back in 1995, the brothers who started the Masjid converted a store into a place for the worship of Allah The Most High. It is also known by the name, Tawheed Center of Detroit. Since 1995 the community has Alhamdulilah grown and so has the Masjid. Right next to the small old Masjid was built a new Masjid which has been in use since the year 2001. The old Masjid was converted to a full time Islamic school. Today the school offers Islamic Education to about 100 Muslim children from Kindergarten to 7th Grade for boys and girls.','7.21576E+16','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800828917&SEARCH_TYPE=1','NULL'),
    (58,'Masjid As-Salam Islamic Community Center','21628 Fenkell Street Detroit, MI','NULL','NULL','African','NULL','2008','NULL','2008','NULL','NULL','This congregation began on West 7 Mile and moved to this location in 2008.','7.21576E+16','https://www.facebook.com/pages/Islamic-Community-of-As-Salaam/109718369092478','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800906106&SEARCH_TYPE=1','NULL'),
    (59,'Masjid Baitul Mukarram and Islamic Academy','12203 Conant Street Hamtramck, MI','(313) 258 - 1238','http://www.baitulmukarrammasjid.org/','South Asian','NULL','2003','2003','NULL','NULL','This mosque is opened for the five daily prayers and provides Islamic educational services for familys. A major renovation project was completed in 2015, providing much more room for congregational prayers and educational programs. ','This masjid came together in the early 2000s and reflects the rapid growth of the Bangladeshi Muslim community in Detroit and Hamtramck. It is an offshoot of Masjidun-Nur. ','7.21576E+16','https://www.facebook.com/baitulmukarramdetroit','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800893925&SEARCH_TYPE=1','Gazanfar Chowhury, Syed Iqbal H. Kchowdhury, Khurshid Alam, Abdur Rob, Abdul K. Choudhry'),
    (60,'Masjid Bilal','1525 N. Ridge Road Canton, MI','734-489-1669','https://www.masjidbilalcanton.org/','African American','NULL','1990''s','NULL','2007','NULL','NULL','The Masjid Bilal community first organized in the late 1990''s.  They opened a mosque and school in Ypsilanti in 2007, in a converted house.  They purchased this former church in Canton and converted it into a mosque in 2011.  Both masajid are open for daily prayers and provide educational programs for young adults.','NULL','https://www.facebook.com/pages/Masjid-Bilal-Canton-Mi/777953062318088','NULL','NULL','NULL'),
    (61,'Masjid Bilal/Madrasah Bilal','4891 W. Michigan Avenue Ypsilanti, MI','NULL','http://www.masjidbilalmi.org','Mixed','NULL','6/12/2006','NULL','2007','NULL','NULL','The Masjid Bilal community came together in the late 1990''s.  In 2005 they opened a school to teach the memorization of the Quran.  In 2007 they moved to this space along with the mosque.  They are affiliated with Masjid Bilal in Canton as well.  Both masajid are open for daily prayers.','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800909753&SEARCH_TYPE=1','NULL'),
    (62,'Masjid Madinatul Ilm','37775 Palmer Road   Westland, MI','(734) 834-9296','http://www.masjidmadinatulilm.com/','South Asian','NULL','2013','2013','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/masjidmadinatulilm/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800937980&SEARCH_TYPE=1','Qadi Ilyas, Muhammad Ammar, Muhammad Numan'),
    (63,'Masjid Mahmood','1445 W. Auburn Road Rochester Hills, MI','NULL','NULL','South Asian','NULL','2008','2008','NULL','NULL','NULL','Ahmadiyyah Muslim Community Center Grand Opening, Ramadan 2008.','7.21576E+16','https://www.facebook.com/pages/Ahmadiyya-Muslim-Community-Center/113856421979466','NULL','NULL','NULL'),
    (64,'Masjid Mu''ath Bin Jabal','6096 Dorothy Street Detroit, MI','(313) 571-9502','NULL','Arab','NULL','4/17/1978','12/19/1976','NULL','NULL','Mu‘ath Bin Jabal is a focal point for the growing population of Yemeni immigrants who live along the border of Hamtramck and Detroit. Small shops that cater to Yemenis line the streets next to the mosque. Young men socialize in front of the local grocery, speaking a mélange of Arabic and English, while bicycle brigades of Yemeni children cruise the streets. The neighborhood was blighted and dangerous when Yemenis starting moving there in the 1970s, but the degraded housing stock was cheap. Over the last 20 years, Yemeni workers have bought and repaired dozens of houses and, in increasing numbers, have brought their wives and children to Detroit. Their school, mosque, and stores are the infrastructure of a stable, socially and morally conservative enclave that has excellent relations with the Detroit police, the public school system, and city government, all of whom appreciate the grassroots urban reclamation project the Yemenis are running in their slice of Detroit.','Masjid Mu‘ath Bin Jabal is located at the center of a Detroit neighborhood that is almost entirely Yemeni. Established in 1976, the mosque began as a prayer space in a coffee shop. It is housed today in an old church building with an attached charter school. The sanctuary of the church has been substantially enlarged and now serves as a prayer space that can easily accommodate a thousand men. A large space for women has been set aside upstairs.','7.21576E+16','https://www.facebook.com/MasjidMuath/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800869932&SEARCH_TYPE=1','NULL'),
    (65,'Masjid Nasrullah','15744 Harper Detroit, MI','NULL','http://www.naicom.info/','African','NULL','2007','2007','2007','NULL','NULL','Nigerian American Islamic Community of Michigan.  The congregation moved to this facility in 2007.  Before that they were members of Muslim Community Center of Detroit previously located on Marlborough.','7.21576E+16','NULL','NULL','NULL','NULL'),
    (66,'Masjid Saaliheen (American Society of Muslims Masjid of Detroit, Inc.)','20823 W. Chicago Detroit, MI','NULL','NULL','African American','NULL','2000','NULL','NULL','10/1/2010','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800852965&SEARCH_TYPE=1','Hamin Rasool, Osman Almanza, Intisar Abdulghani'),
    (67,'Masjid Umar bin Khattab','18105 Racho Road Brownstown, MI','NULL','http://brownstown-masjid.com','South Asian ','NULL','1994','1994','NULL','NULL','This is an effort to rekindle our spirituality and strengthen our relationship with our Creator. Where we can meet our fellow Muslim brothers/sisters and renew our sense of belonging.The goal is to build the bond of community through love and cooperation while seeking Allahs pleasure. Our role as Muslims in this community is to get involved and actively participate in Masjid events in order to reach our common goal of striving to please Allah (swt) through connecting our hearts to the masjid, Insha''allah.','NULL','7.21576E+16','https://www.facebook.com/pages/category/Mosque/Masjid-Umar-bin-Khattab-BrownstownMI-205984269414564/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800877141&SEARCH_TYPE=1','NULL'),
    (68,'Masjid Uthman bin Affan','21380 Ryan Road Warren, MI','(536) 510-4240','https://www.masjiduthmanbinaffan.org/','South Asian','NULL','1999','1999','NULL','NULL','Masjid Uthman-bin-affan has noticed the need of a masjid in the city of warren in the year of 2010, Alhamdullilah this project was successful, thereon we have also noticed the need for the youth of Warren, therefore we have started Maktab Quran classes in the evening for boys and girls from Monday to Thursday.The zeal and the thirst of knowledge of deen grew for youths and adults,Masjid Uthman-bin-Affan thereafter started full time hifz and aalim course classes and has tutoring programs for academics. Inshallah Masjid Uthman-Bin-Affan has many project ahead that will benefit muslims residing in the city of warren, Detroit metro area and surrounding communities. We also ask for your help by making dua for us.','Masjid Uthman-Bin-Affan is a non profit, independent organization which was established in the year of 2010.  The prime goal of the Masjid Uthman-Bin-Affan is to foster and create an Islamic environment for the Muslim community in the city of Warren by providing religious,and educational activities for its members and the members of the public at large.','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800842204&SEARCH_TYPE=1','NULL'),
    (69,'Masjid Wali Muhammad','11529 Linwood Avenue Detroit, MI','(313) 868-2131','https://www.historicmwm.com/?fbclid=IwAR2Fh31c1bFo4Y-_QUR5DBBApkVXPifbjjNFCAJuGlbrlojsJmKfQLukqgI','African American','NULL','1954','1957 (from Black Bottom)','NULL','NULL','Masjid Wali Muhammad is located on the upper level of a two-story building which was originally a Jewish community center. The lower level holds a large kitchen, a computer room, and a spacious meeting/dining room. The masjid is active in the community, holding weekly fundraisers and sponsoring a local soup kitchen. The mosque is attended by a largely African American, native-born congregation and is affiliated with the national leadership of Imam Warith Deen Mohammad. Gary al-Kasib is the mosque’s current imam.','Masjid Wali Muhammad is home to the first and oldest African American Muslim congregation. Although located in its current facility on Linwood Avenue since 1954, its first home was on Hastings Street, in Detroit’s “Black Bottom.” It was there that the Nation of Islam was founded by W.D. Fard and led by the Honorable Elijah Muhammad in the early 1930s. The congregation’s name changed from Muhammad’s Temple No. 1 to Masjid Wali Muhammad in 1978, when the Honorable Warith Deen Muhammad led the former Nation of Islam into Sunni Islam. Masjid Wali Muhammad was rededicated as a mosque open for the five daily prayers, with a conventional prayer space (without chairs) oriented toward Mecca.','7.21576E+16','https://www.facebook.com/historicmwm/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800801029&SEARCH_TYPE=1','Lemuel J. Hassan, Harold D. Gaines, Charles D. Oliver'),
    (70,'Masjidun-Nur','11311 Mound Road Detroit, MI','(313) 892-5450','http://www.masjidunnur.org/','South Asian','NULL','1977 (on Pilgrim in Highland Park)','NULL','NULL','NULL','NULL','This congregation was incorporated in 1977 in Highland Park, but also made use of a former gas station for prayers at this location on Mound Road in Detroit. Originally comprised of a diverse South Asian community, the mosque today is primarily of Bangladeshi origins. The mosque recently completed a new renovation and expansion.  Among the oldest congregations in Detroit, Masjidun-Nur anchors the "Islamic Village" that has now taken shape on the border of Hamtramck and Detroit.  Like its siter mosque in Highland Park, this congregation is associated with the Tablighi Jumaat movement.','7.21576E+16','https://www.facebook.com/pages/Masjidun-Nur-of-North-East-Detroit/115445298485150','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800843146&SEARCH_TYPE=1','Syed Anwar Miah, Oajib Ullah, Abdul M. Barlaskar, Mohammed Tahir Ali, Telal Ali, Mohammed M. Rahman, Alibur Rahman Shahid, Ahmed Rahman Choudrey, Shareef Abdul Aziz, Syed Abdul Monnan, Abdul Hye'),
    (71,'Michigan Islamic Center of U.S.A.','24134 Warner Warren, MI','NULL','NULL','NULL','NULL','2009','2009','NULL','10/1/2012','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800922564&SEARCH_TYPE=1','Mujibur Rahman, Kabir Ahmed, Monzur K. Shafi, Gulam Y. Chowdhury'),
    (72,'Mohammadia Madrasha, Inc. and Quran Learning Center ','4541 Garvin Street Detroit, MI','(561) 502-6589 / (313) 377-9245','http://www.quran4you.com','South Asian','NULL','2002','2002','NULL','NULL','In addition to being open for prayers five times a day, the Center now provides Quran, Tajweed, and Islamic studies programs after school and on weekends, summer intensives, social services, and support for new Muslims. We have also been able to expand our reach to the Ann Arbor, Canton, and Dearborn communities, offering weekly and weekend Quran classes there as well.','The Quran Learning Center is a non-profit 501(c)3 educational school founded in 2002 dedicated to teaching current and future generations Islamic knowledge. The Center is located in Detroit on the edge of Hamtramck, one of the largest and most diverse Muslim communities in Michigan. Alhamdulillah, the Quran Learning Center has grown substantially since 2002. ','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800891428&SEARCH_TYPE=1','Meer Hossain'),
    (73,'Moorish Science Temple (#25)','5601 Grand River Blvd. Detroit, MI','NULL','NULL','African American ','NULL','1928','1996','1996','NULL','NULL','The Moorish Science Temple of America Number 25 was located in downtown Highland Park, from the 1940’s through the 1960s, and at 910 Bryson Street, near the intersection of East Seven Mile Road and Woodward Avenue, from 1968-1994. Since 1994, it has been at its current location on Grand River Avenue, in a former bank building. The interior is triangular in shape, similar to a pyramid. In the front there is a pulpit, an altar with a picture of Noble Drew Ali over it, and both the American and Moroccan flags. Picture of Noble Drew Ali, Marcus Garvey, and a copy of the Moorish Constitution decorate the walls.','7.21576E+16','https://www.facebook.com/pages/Moorish-Science-Temple-of-America-Inc/113410425359091','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=801070576&SEARCH_TYPE=1','NULL'),
    (74,'Muhammad''s Mosque #1','14880 Wyoming Street Detroit, MI','NULL','http://www.noidetroit.org/','African American','NULL','1984','NULL','NULL','NULL','NULL','This mosque was incorporated with the State in 1984 by Nathan Muhammad, David Faison and Thomas Williams.  It is associated with the Nation of Islam.','7.21576E+16','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800898168&SEARCH_TYPE=1','Nathan Muhammad, David Faison, and Thomas Williams'),
    (75,'Muhammadi Islamic Center ','2075 Fort Street Lincoln Park, MI','(734) 564-1650','NULL','Bangladeshi','NULL','June, 2015','2015','NULL','NULL','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800943127&SEARCH_TYPE=1','Adnan H. Hanif'),
    (76,'Muslim Center of Detroit','1605 Davison West Detroit, MI','(313) 883-3330','https://muslimcenterdetroit.com/','African American','NULL','1984','NULL','NULL','NULL','The Muslim Center’s new facility includes a large prayer hall, a gym, a social hall, classrooms, a kitchen, and administrative offices. Located in a poor urban neighborhood, the Center has an activeda`wa (missions) board that provides a wide array of services to local families and youth, including counseling, job training, a soup kitchen, and substance abuse programs. Working with New Detroit, Inc., the Muslim Center also provides a summer camp and athletic programs for local young people. Led by Imam Derrick Ali, the center is also active in interfaith work and hosts an annual interfaith Thanksgiving dinner. With a largely African American and African immigrant congregation, the Center is open to all believers and is especially adept at making visitors feel welcome.','While the Muslim Center of Detroit traces its immediate history to the establishment in 1985 of the Muslim American Society by Imam Warith Deen Muhammad, the community’s history extends ultimately to the 1930s, when the Nation of Islam was first established in Detroit by Warith Deen’s father, Elijah Muhammad. The mosque is located on Davison Avenue in Detroit, in an old stone building that was once a bank. The mosque underwent significant expansion and renovation in 2005.','7.21576E+16','https://www.facebook.com/Muslim-Center-Detroit-131716183660789/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800813460&SEARCH_TYPE=1','NULL'),
    (77,'Muslim Community Center of Detroit','13720 W. McNichols Road Detroit, MI','(313) 427-2554','NULL','African','NULL','2008','NULL','NULL','NULL','NULL','Dedicated in August 2008.  The congregation is primarily, but not exclusively, from Nigeria.','7.21576E+16','https://www.facebook.com/pages/Muslim-Community-Center-of-Detroit/113924605305184','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800886225&SEARCH_TYPE=1','NULL'),
    (78,'Muslim Community Mosque (Islamic Cultural Association)','35700 W. 12 Mile Rd.  Farmington Hills, MI','(248) 488-5600','http://ica-mi.org/','Syrian','NULL','10/25/2000','NULL','NULL','NULL','The Islamic Cultural Association''s mission is to serve as a religious and social resource for its members as well as other Muslims in the area by actively providing religious, social, and other services.','The Islamic Cultural Association was founded by a group of families who hoped to establish an Islamic community that modeled their beliefs and values.','NULL','https://www.facebook.com/MichiganICA/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800865112&SEARCH_TYPE=1','NULL'),
    (79,'Muslim Community of Macomb (Baitul M`amur)','38810 Ryan Road Sterling Heights, MI','(313) 910 – 4817','http://www.muslimcommunitymacomb.org/','Bangladeshi','NULL','2010','NULL','NULL','NULL','We serve the Muslim communities in Troy, Sterling Heights, Warren and Madison Heights. We offer five daily prayers, regular Jummu’ah prayers, weekly halaqa, youth programs and community events.','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800923905&SEARCH_TYPE=1','Abdul Matic, Koysor Jaigirdar, Jamshed Choudhury, Mohammed Murshed Ahmed, Saiful H. Ali'),
    (80,'Muslim Community of the Western Suburbs','40440 Palmer Canton, MI','(734) 729-1000','http://www.mcws.org','Mixed','NULL','1988','NULL','NULL','NULL','The Muslim Community of the Western Suburbs is dedicated to creating and promoting a community of peace and caring where it and its members grow closer to God and through that closeness become positive contributors to their families and the community around them. As such MCWS lauds and welcomes acts of community service, neighborliness, and positive civic participation. Conversely MCWS stands against acts of violence, oppression, abuse and discrimination whether committed by those external to the Muslim community or from within. We pray for a world where peace and harmony prevails and the poor, oppressed, and abused are relieved of their challenges.','The MCWS was founded in 1977 as a group of young Muslims living in this area realized that as their toddlers grew older, they had to seriously think about their identity and place as American Muslims in the giant melting pot of the USA.  These parents were concerned as they saw the troubling situation of many Muslim families in the area who had lost their Islamic values and identity due to lack of knowledge and practice of their deen. This was a future that these Muslim parents wished to avoid.They took the challenge very seriously and resolved to create a stronger foundation for their children to maintain their Islamic identity and values. Along with this challenge was that of the parents’ own lack of knowledge of Islam. They realized that without a well-rooted understanding and practice of Islam themselves; they would be ill-equipped to impart the much-needed strong Islamic values to their own children. These parents, when growing up, were bound to the values and practices prevalent among their own societies, and were still part of a cultural milieu present at the time in their own countries. They felt the need to gain Islamic education in order to convey accurate Islamic values and ideals. These challenges had to be met, and thus, the young parents began the journey to where we are today.','7.21576E+16','https://www.facebook.com/mcws.org/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800792772&SEARCH_TYPE=1','NULL'),
    (81,'Muslim Men in Fellowship Unity','17935 John R Street Highland Park, MI','NULL','NULL','African American','NULL','12/2/1992','NULL','NULL','10/1/2007','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800837340&SEARCH_TYPE=1','NULL'),
    (82,'Muslim Unity Center','1830 W. Square Lake Road Bloomfield Hills, MI','(248) 857-9200','http://www.muslimunitycenter.org/','Syrian','NULL','1993','NULL','NULL','NULL','The Muslim Unity Center (MUC) is a non-profit, Islamic organization recognized as tax-exempt entity under U.S. Internal Revenue Code section 501(c)(3). The objective of MUC is to develop, support and promote an Islamic way of life and to ensure the emergence of an American Muslim identity. MUC affirms the principles of the social order established by the Prophet Muhammad (Peace Be Upon Him), including the establishment of a thriving and vibrant community free of ethnic, racial, cultural or national divisions. MUC''s vision is based on the teachings of the holy book Al-Qur''aan and by the teachings of the Prophet (PBUH)','The Unity Center was established in 1993 by Victor Begg and other Muslims living in the northern suburbs of Detroit who felt a need to develop an Islamic center in the area. They saw it as a part of the metropolitan area that had a growing Muslim population, but the closest mosque was 15 miles away. In addition, the Unity Center was to be a place where not only a variety of ethnic groups would come together, but a place where a variety of schools of thought within Islam would be welcome.','7.21576E+16','https://www.facebook.com/TheMuslimUnityCenter/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800895494&SEARCH_TYPE=1','NULL'),
    (83,'Rayyan Center','46441 Five Mile Road Plymouth, MI','(248) 347-6681','https://www.rayyancenter.org/','South Asian','NULL','4/28/2009','NULL','NULL','8/19/2014','NULL','NULL','NULL','https://www.facebook.com/rayyancenter/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800920877&SEARCH_TYPE=1','NULL'),
    (84,'Tawheed Center','29707 W. 10 Mile Road Farmington Hills, MI','(248) 426-7360','http://www.tawheedcenter.org','Mixed','NULL','1993','NULL','NULL','NULL','NULL','NULL','7.21576E+16','https://www.facebook.com/tawheed.center/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800845806&SEARCH_TYPE=1','NULL'),
    (85,'Tawheed Center of Novi','24101 Novi Road Novi, MI','NULL','https://novitawheedcenter.org/','Mixed','NULL','10/14/2011','NULL','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/tawheed.centre.9','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800931684&SEARCH_TYPE=1','NULL'),
    (86,'The Qur''an and Sunnah Society','19800 Van Dyke Detroit, MI','(313) 893-3763','http://www.qss.org/','African American','NULL','4/17/1992','NULL','NULL','NULL','The goal of al-Qur''an was Sunnah Society is to invite people to Islaam, to help them understand it, practice it, and purify themselves with it, all in accordance with the blessed Manhaj of the Salaf.','NULL','7.21576E+16','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=801069322&SEARCH_TYPE=1','NULL'),
    (87,'Tijani Zawiya','3777 Parker Street Detroit, MI','NULL','NULL','African American','NULL','2001','NULL','NULL','NULL','NULL','NULL','7.21576E+16','NULL','NULL','NULL','NULL'),
    (88,'United Masjid Council of Michigan','2733 Caniff Hamtramck, MI','NULL','NULL','NULL','NULL','2005','NULL','NULL','NULL','NULL','NULL','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800901528&SEARCH_TYPE=1','Muhammad Muyeen Uddin, M. Abdul Latif Azom, Moynul Islam, Hafiz Rayhan Uddin, AbuSayed Mahfuz, Abdul Motlib'),
    (89,'University Islamic Center of Detroit/Cass Mosque','4646 Cass Avenue Detroit, MI','(313) 831-9222','NULL','Mixed','NULL','1979','NULL','NULL','NULL','NULL','This group first incorporated in 1979 as Universal Moslems, Inc.  Their founding members are notably from a variety of ethnic backgrounds, including Mohamed Abdel-Wahab, Zeinab Abdel-Wahab, Wayel Zenalabidin, Malik Salaam, Syiedal Salaam, Adam Shakoor, Jamil Kettan, Ayesha Muhammad.  They completed a major renovation and doubling of their square footage in 2005.  This mosques serves the Wayne State University community and attracts many worshipers from downtown Detroit as well.','7.21576E+16','https://www.facebook.com/cassmosque/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800887571&SEARCH_TYPE=1','Mohamed Abdel-Wahab, Zeinab Abdel-Wahab, Wayel Zenalabidin, Malik Salaam, Syiedal Salaam, Adam Shakoor, Jamil Kettan, Ayesha Muhammad'),
    (90,'Zainabia Center/Ahlebait Association of Michigan','2230 Crumb Road Walled Lake, MI','(248) 669-5740','http://www.zainabia.org/v1/index.aspx','South Asian','NULL','2007','NULL','NULL','NULL','NULL','Ahlebait Association of Michigan.  The new masjid was dedicated in 2007.  ','7.21576E+16','https://www.facebook.com/Zainabia.CenterofMI','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800923490&SEARCH_TYPE=1','NULL'),
    (91,'Ahmadiyya Mission (Historic, 1953)','2151 Grand Blvd. Detroit, MI','NULL','NULL','African American','NULL','1950','1950','NULL','1975','NULL','Ahmadiyya Movement in Islam circa 1949-1950''s.  This mission was headed by Syed Jawad Ali who arrived in America in 1949.  This was one of only five Mosques that the Ahmadiyyah had active in 1953.','NULL','NULL','NULL','NULL','Syed Jawad Ali'),
    (92,'Ahmadiyyah Islamic Center (Historic, 1952)','1241 Burlingame Detroit, MI','NULL','NULL','NULL','NULL','1952','NULL','NULL','1953','NULL','Home of Dr. M. Yusuf Khan, missionary to US, 1952.  Referenced as "Islamic Center" in Detroit News article.','NULL','NULL','NULL','NULL','NULL'),
    (93,'Ahmadiyyah Mission (Historic, 1921)','27 Labelle Street Highland Park, MI','NULL','NULL','NULL','NULL','1921','NULL','NULL','NULL','NULL','Mufti Mohammed Saddiq was given a large apartment by October 1921, in this apartment building owned by Mohammed Karoub.  Mufti Saddiq used this apartment as a Ahmadiyyah Mission for 6 months before his conflict with the Karoub brothers led him to establish his better known mission in Chicago.','NULL','NULL','NULL','NULL','NULL'),
    (94,'Ahmadiyyah Moslem Mission (Historic, 1933)','537 Hendrie Street Detroit, MI','NULL','NULL','NULL','NULL','1933','NULL','NULL','1950','NULL','The Ahmadiyyah established a mission here in 1933.  Previously, they worked out of several locations on Victor and LaBelle in Highland Park.  Note the proximity of this location to Paradise Valley.','NULL','NULL','NULL','NULL','NULL'),
    (95,'Al-Aqabah Islamic Community Center (Historic, 2011)','12818 Joseph Campau Detroit, MI','NULL','NULL','NULL','NULL','2009','2011','NULL','2014','NULL','Community formed in December 2009.  Masjid Al-''Aqabah opened in March 2011.','7.21576E+16','NULL','NULL','NULL','NULL'),
    (96,'Al-Mumineen Mosque (Historic, 1980''s)','15535 W. McNichols Road Detroit, MI','NULL','NULL','NULL','NULL','1980''s','1980/1981','NULL','1981','NULL','The Al-Mumineen congregation moved to this located at McNichols in 1980 or 81 from their long standing location at 1554 Virginia Park Avenue, after the death of Othman Hassanein.  The congregation remained at this address through the mid 80''s under the leadership of Seli Khalid.  Some members of this group eventually merged with Masjid al-Nur.','NULL','NULL','NULL','NULL','Othman Hassanein'),
    (97,'Al-Mumineen Mosque/Virginia Park (Historic, 1947)','1554 Virginia Park Avenue Detroit, MI','NULL','NULL','African American','NULL','1947','NULL','1978','1981','NULL','This mosque was first established as the Universal Muslim Brotherhood of Al-Islam in America in 1947 by Hajj Ismael Sammsan.  In 1952 it was incorporated with the State of Michigan as the Jajj Sammsan Abdullah Mosque (Islamic Mission).  This was the first documented African American mosque in Detroit.  The congregation was Sunni Muslim, and not affiliated in any way with the Nation of Islam orthe Ahmadiyah.  In 1966, it changed its name to the Mumineen Mosque, or Masjid al-Mamineen.  Othman Hassanein was the chairperson of the mosque for many years, through the 1970''s.  Hassanein and Hussein Karoub (and later Mike Karoub) studied the Quran together and somties exchanged pulpits.  This mosque was also frequented by Tablighi Jumaat missionaries form the 50''s-70''s.  When Hassanein died in the late 70''s, his son-in-law, Imam Khalid, took over as leader.  Eventually it moved to a location on McNichols and the house was torn down.','NULL','NULL','NULL','NULL','Hajj Ismael Sammsan'),
    (98,'Albanian American Moslem Society of Detroit (Historic, 1950''s)','19775 Harper Ave Harper Woods, MI','(313) 884-6676','NULL','NULL','NULL','11/21/1945','1950','1963 (See Albanian Islamic Center)','1959 (See Albanian Islamic Center)','NULL','Hamilton and Calvert (1949-1959).  The group sold this building in 1959, worshipped at the American Moslem Society for a year or so, and then eventually opened the Albanian Islamic Center in Harper Woods in 1961.','NULL','NULL','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800870937&SEARCH_TYPE=1','NULL'),
    (99,'Allah Temple of Islam (Historic, 1932)','283 E. Hancock Detroit, MI','NULL','NULL','NULL','NULL','1932','NULL','NULL','NULL','NULL','According to Karl Evanzz (82), this is where Fard Muhammad had his first "mosque" in 1932 and where he renamed Elijah Poole, Elijah Karriem, and announced he would become "supreme minister" of the Allah Temple of Islam.','NULL','NULL','NULL','NULL','Fard Muhammad'),
    (100,'American Islamic Institute (Historic, 1979)','3642 Karen Pkwy Waterford, MI','NULL','NULL','NULL','NULL','1979','NULL','NULL','1990','NULL','This group incorporated in February of 1979. The address provided is that of the group''s founder, Nihad Hamed.  The incorporating members were all former leaders of the American Moslem Society in Dearborn.  They had recently lost control of the AMS, the mosque their families had founded, in a bitter lawsuit and this Institute represents the group''s first effort to reincorporate and start again.  Imam Mohammed Karoub, Robert Simons, Fatme Boumrad, Aida Karoub, Fadwa Alsaid, Selma Hegasi, Julia Jabara, and Kel Jabara''s names are those provided.  Their articles of incorporation are many.  Among them is an emphasis on the education of the American public about Islam, the education of the American-born Muslims, and the goal of building, leasing, or constructing a "mosque".  It isunclear how long this Institute survived.  Many of their members reorganized in 1981 as the American Moselm Bekaa Center (see above), which opened in Dearborn in 1982.','NULL','NULL','NULL','NULL','Nihad Hamed'),
    (101,'American Islamic League of Bekaa (Historic, 1979)','10605 West Warren Dearborn, MI','NULL','NULL','NULL','NULL','1979','NULL','NULL','1981','NULL','This group was established in June of 1979, shortly after its founders lost a legal battle filed against the new leadership of the Merican Moslem Society, established a generation earlier by these same men and their families.  The AMS is the oldest mosque currently active in Michigan.  The group changed their name to the American Muslim Bekaa Center and opened a facility on Chase Road in Dearborn in 1982.  This mosque is still active.  Mike AlcodrayAbdel Majid KadryAli SiajeMounir Jouma when the group first changed their name in 1981 Hussein El-Hage''s name is also listed in the paperwork.','NULL','NULL','NULL','NULL','NULL'),
    (102,'American Muslim Mission Islamic Center (Historic, 1984)','2940 Mt. Elliot Detroit, MI','NULL','NULL','NULL','NULL','1984','NULL','NULL','1990','NULL','Established in 1984 by Abdul Raheem Rashed, Wali Deen Muhammad, and Harold Rahim, it is unclear how long this group was active.','NULL','NULL','NULL','NULL','Abdul Raheem Rashed, Wali Deen Muhammad, and Harold Rahim'),
    (103,'American Society of Muslims Masjid of Detroit (Historic, early 2000''s)','20823 West Chicago Street Detroit, MI','NULL','NULL','NULL','NULL','2004','NULL','NULL','2010','NULL','Masjid Al-Saliheen, active as of 2004.','NULL','NULL','NULL','NULL','NULL'),
    (104,'Assira Jadeed Society (Historic, 1940''s)','2809 Salina Dearborn, MI','NULL','NULL','NULL','NULL','1940''s','NULL','NULL','1950','NULL','The New Generation Society is listed in Dearborn City Directories at this address in the 1940''s.  It is not known if this society was religious in orientation, but the name resembles that of the Islamic association that established the first mosque in Cedar Rapids in teh 1930''s.','NULL','NULL','NULL','NULL','NULL'),
    (105,'Communaute Islamique Africaine: La Paix de Michigan Masjid','20555 Lahser Rd. Detroit, MI','NULL','NULL','NULL','NULL','2001','NULL','NULL','2004','NULL','NULL','NULL','NULL','NULL','NULL','Souleymane Doukoure, Aboubaker S. Kone, Kone Amana'),
    (106,'Detroit Mosque (Historic, 1945-50)','14075 Dequindre Detroit, MI','NULL','NULL','NULL','NULL','1945','NULL','NULL','1950','NULL','MIA small congregation of black Muslims met at this location from 1945-1950, roughly.  This is the location where Satohata Takahashi is said to have led a congregation.','NULL','NULL','NULL','NULL','NULL'),
    (107,'Hindoo Hall (Historic, 1930''s-50''s)','1003 Hastings Street Detroit, MI','NULL','NULL','NULL','NULL','1930''s','NULL','NULL','1950''s','NULL','This coffee shop is where Indians and Afghanis met for prayers, especially holiday prayers in the 1930''s.  Later known as the India Club, the New India Club, and the India-Pakistan Club.  Moved to Gratiot and Grand Blvd in the late 50''s when Hastings was plowed under in the name of urban renewal.','NULL','NULL','NULL','NULL','NULL'),
    (108,'Islamic Center of America (Historic, 1963-2005)','15571 Joy Road Detroit, MI','NULL','NULL','NULL','NULL','1963','NULL','2005','2005','NULL','Dedicated September 20, 1963 as the Islami Center of Detroit.  Opened new facility on Ford Road in Dearborn in 2005.  This historic mosque is now home to the al-Zahraa Islamic Center.','NULL','NULL','NULL','NULL','NULL'),
    (109,'Islamic Institute of Knowledge (Historic, 1983-1998)','13500 W. Warren Avenue Dearborn, MI','NULL','NULL','NULL','NULL','1982','NULL','1998','1998','NULL','The Islamic Institute of Knowledge was incorporated with the State of Michigan in 1982, with Sheikh Abdul Latif Berry as their spirtual leader.  They opened their doors at this location, a former bank, in 1983 and remained here until moving to their new location on Shaefer Road in 1998.  The congregation is primarily from South Lebanon, and it grew tremendously during the Leanese civil war when large numbers of Lebanese citizens sought refuge with friends and family in Detroit.  Today this congregation anchors, along with the Islamic Center of American, the Shia population of Dearborn and its surrounding communities.','NULL','NULL','NULL','NULL','Sheikh Abdul Latif Berry'),
    (110,'Jamiyatul Nasrul Ilm (Historic, 1990''s)','9309 Oakland Detroit, MI','NULL','NULL','NULL','NULL','1990','NULL','NULL','1998','NULL','Grew out of the Masjid As-Salaam Orthodox Islamic Movement.  Was active from 1990-1998.','NULL','NULL','NULL','NULL','NULL'),
    (111,'Lebanese Islamic Association of Michigan (Historic, 1988)','7250 Chase Dearborn, MI','NULL','NULL','NULL','NULL','1988','NULL','NULL','1990','NULL','Incorporated by Hassan Al-Habhab with the State in 1988, this group began renovating a new facility at this address, but did not last very long.  Today, this address is home to the Byblos Banquet Hal which has no association with the former residents.','NULL','NULL','NULL','NULL','Hassan Al-Habhab'),
    (112,'Masjid Al Haqq','4017 Clairmount Detroit, MI','NULL','NULL','African American','NULL','1986','NULL','NULL','2013','NULL','NULL','NULL','NULL','NULL','NULL','Imam Luqman Abdullah, Sharif A. Muhammad, David Adams'),
    (113,'Masjid al-Asr (Historic, 1977)','9819 Dexter Blvd. Detroit, MI','NULL','NULL','NULL','NULL','1977','NULL','NULL','1985','NULL','This was an offshoot of Masjid As-Salaam Orthodox Islamic Movement, which united with the Dar-ul Islam Movement and incorporated in 1977 as Ikhwanul Muslimun and established Masjid al-Asr, initially at 8962 Mackinaw, Detroit.  The incorporating members were named Musa Abdul Mujib, Muhammad Saber, Dwight Hawkins, Yusuf Hakim, and Shukri Abdul Karim.  Masjid al-Haqq can also trace its origins to this congregation','NULL','NULL','NULL','NULL','Musa Abdul Mujib, Muhammad Saber, Dwight Hawkins, Yusuf Hakim, and Shukri Abdul Karim'),
    (114,'Masjid al-Haqq (Historic, 1981-2009)','4118 Joy Road Detroit, MI','NULL','NULL','NULL','NULL','1981','NULL','NULL','NULL','NULL','This small congregation has had financial difficulties in recent years and was foreclosed on by the city in 2009.  It reopened that same year at 4017 Clairmount Street.  Originally led by Imam Luqman Abdullah, who was shot and killed by the FBI in 2009, the group is now led by his son.','NULL','NULL','NULL','NULL','Imam Luqman Abdullah'),
    (115,'Masjid Al-Iklas (Historic, 1988-2004)','16412 E. Warren Avenue Detroit, MI','NULL','NULL','NULL','NULL','1995','NULL','NULL','2005','NULL','NULL','7.21576E+16','NULL','NULL','NULL','Shahied Hanif, Gary Al-Kasib, Abdullah Lahab, Nadir S. Ahmed'),
    (116,'Masjid As-Salaam Orthodox Islamic Movement (Historic, 1969-1980)','12537 Hamilton Highland Park, MI','NULL','NULL','NULL','NULL','1969','NULL','NULL','1980','NULL','This group incorporated with the state in 1971, but began meeting in 1969 or thereabouts.  As members began to accept different ideologies in the late 1970''s and 80''s, this gave rise to several new mosque communities including Asr Mosque (Masjid al-Asr), Masjidun Nur (Masjid An-Nur), Jamiyatul Nasrul Ilm and the Tijani Zawiya.  Though the masjid ceased operation in the 1980''s, the organization is still incorporated and active.','NULL','NULL','NULL','NULL','NULL'),
    (117,'Masjid As-Salam (Historic, 2000''s)','21230 W. 7 Mile Road Detroit, MI','(586) 945-6855','NULL','African','NULL','2003','2003','2008','2008','NULL','This West African congregation moved to 21628 Fenkell in 2008.','NULL','NULL','NULL','NULL','NULL'),
    (118,'Masjid John Hasan (Historic, 1979-1984)','MI','NULL','NULL','NULL','NULL','1979','NULL','NULL','1984','NULL','Talib Karim, the "resident imam" of this mosque hosted a dedication ceremony and banquet at the mosque in Highland Park on January 27, 1979 (Muslim STAR 2/79), providing prayers and a tour of the new facility.  The precise address is not known, but this group was affiliated with the World Community of Al-Islam in the West, the ministry of Imam Warith Deen Mohammad.  It is likely to have been converted from a former NOI Temple.  This congregation seems to have joined the Muslim Center of Detroit when it incorporated in 1984.','NULL','NULL','NULL','NULL','Talib Karim'),
    (119,'Masjid Oak Park (Historic)','15425 Miller Street Oak Park, MI','NULL','NULL','NULL','NULL','1999','1999','NULL','2005','NULL','This masjid was formed by a group of neighbors who realized they were renting space in the same apartment complex.  A super gave them permission to clear out an unused basement for religious services and the space became known to other Muslims who lived and worked near the facility.  They closed in 2005 after other mosque facilities became available nearby.','NULL','NULL','NULL','NULL','NULL'),
    (120,'Masjid Saaliheen (Historic)','22726 Rein Street Eastpointe, MI','NULL','NULL','NULL','NULL','2000','NULL','NULL','2004','NULL','An American Society of Muslims Masjid, established in 2000.  Folded in 2004.','NULL','NULL','NULL','NULL','NULL'),
    (121,'Moorish Temple of America #4 (Historic, 1929)','632 Livingstone Avenue Pontiac, MI','NULL','NULL','NULL','NULL','1929','NULL','NULL','1940','NULL','NULL','NULL','NULL','NULL','NULL','NULL'),
    (122,'Moorish Temple of America #4 (Historic, 1929)','1023 Illinois Street Detroit, MI','NULL','NULL','NULL','NULL','1927','NULL','NULL','NULL','NULL','This was the home and first location the Moorish Science Temple led by Governor Lomax-Bey and was incorporated with the State in September of 1927.  The incorporating members included Drew Alin,  James Lomax, Johnny Reynolds, Eddie Watts and Sammy Rucke, all of whom lived in Chicago at the time.  In 1943 Cyrus Nelson El became the registered agent of the group in Michigan and listed his address as 1569 Garfield.  Several resident agents were named over the years until 2005, when the group briefly changed their name to Reincarnate Temple of Detroit and back to Moorish Science Temple again in 2007.','NULL','NULL','NULL','NULL','Led by Governor Lomax-Bey; Incorporating members include, Drew Alin,  James Lomax, Johnny Reynolds, Eddie Watts and Sammy Rucke'),
    (123,'Moslem Mosque (Historic, 1921)','242 Victor Street Highland Park, MI','NULL','NULL','NULL','NULL','1921','NULL','NULL','1927','NULL','1921-1922, first purpose built mosque in the United States.  Built by Mohammad and Hussein Karoub.  Sold to the city in 1927 and torn down.  See Howell 2007 for more information and a photograph.','NULL','NULL','NULL','NULL','Mohammad and Hussein Karoub'),
    (124,'Moslem Welfare Society (Historic)','742 St. Antoine Street Detroit, MI','NULL','NULL','NULL','NULL','1922','NULL','NULL','1930','NULL','President: Mohammed Majid (Satti Majid Muhammad).  This group incorporated in 1922 as a mutual aid society to provide relief for "distressed members, the visitation of the sick, payment of funeral expenses" and to aid orphans and the poor in Turkey.  The group was associated with the Red Crescent Association.  First incorporated in Highland Park, the group moved to this address (date not recorded).','NULL','NULL','NULL','NULL','President: Mohammed Majid (Satti Majid Muhammad); Incorporating members include, Rev. Majid Mohamed of 22 West Street, NY; Romy Omar - 144 Cottage Grove, Highland Park; Joseph Somaf - 142 Victor Avenue, HP; Hassan Husein - 238 Labelle Ave., HP; Mohamed Ahmed - 144 Cottage Grove, HP; Ahmed Hazmey - 151 Gerald Ave., HP.'),
    (125,'Mosque of the Great Kingdom of God (Historic)','5684 Campbell Detroit, MI','NULL','NULL','NULL','NULL','1993','NULL','NULL','2004','NULL','This group seems to have been organized by and for women.  It dissolved in 2004.','NULL','NULL','NULL','NULL','NULL'),
    (126,'Muhammad''s Mosque of Islam #1 (Historic)','1510 Woodward Avenue Detroit, MI','NULL','NULL','NULL','NULL','1980','NULL','NULL','1987','NULL','This group dissolved in 1987.  It''s incorporating members included Minister Paradise Quran Muhammad, Cleo Boyd, and Jasper Boyd.','NULL','NULL','NULL','NULL','Minister Paradise Quran Muhammad, Cleo Boyd, and Jasper Boyd'),
    (127,'Muhammad''s Temple #1 (Historic)','3408 Hastings Street Detroit, MI','NULL','NULL','NULL','NULL','1932','NULL','1957','NULL','NULL','This temple was a former hall located above the entrance to the Castle Theatre, variously identified as the  "former McPherson hall" or "Castle Hall."  This is where Elijah Muhammad established the first home of the Nation of Islam in 1932.  The University of Islam was also opened here in 1934.  The building served as the headquarters of the movement in Detroit until 1957 when it was razed to make way for the Chrysler Freeway.  The community then moved to its present home on Linwood Avenue.  (See Masjid Wali Muhammad.)  The space was originally referred to as Temple No. 1 of the Order of Islam.','NULL','NULL','NULL','NULL','NULL'),
    (128,'Muslim Brotherhood, U.S.A. (Historic)','9031 12th Street Detroit, MI','NULL','NULL','African American','NULL','1959','NULL','NULL','1970','NULL','The Detroit congregation of the Muslim Brotherhood, U.S.A. (an Ahmadiyya affiliate) was established in 1959 by Imam Dawud Ahmad (Denison Echols).  Imam Dawud would have been connected to, or could have been an alias of, Imam Talib Ahmad Dawud, the one time husband of Dakotata Staton (Aliyah Rabia).','NULL','NULL','NULL','NULL','Imam Dawud Ahmad (Denison Echols)'),
    (129,'Muslim Community Center of Detroit (Historic)','5307 Marlborough Street Detroit, MI','NULL','NULL','NULL','NULL','2001','2003','NULL','NULL','NULL','NULL','NULL','https://www.facebook.com/Muslim-Community-Center-of-Detroit-1433032846998956/','NULL','https://cofs.lara.state.mi.us/CorpWeb/CorpSearch/CorpSummary.aspx?ID=800886225&SEARCH_TYPE=1','NULL'),
    (130,'New Masjid and Islamic Education Center','17346 Plainview Detroit','NULL','NULL','NULL','NULL','1994','NULL','NULL','1997','NULL','NULL','NULL','NULL','NULL','NULL','Dawud Alim, Sahirah Muhammad, Osman Almanza, Sr.'),
    (131,'New Mosque/School Building Fund, Inc. (Masjid Wali Muhammads'' Project 90''S, Inc.)','18011 Warrington Detroit','NULL','NULL','African American','NULL','1990','NULL','NULL','1998','NULL','NULL','NULL','NULL','NULL','NULL','Baheejah Shakoor, Dorothy Pasha, Numan Abdulmujees, Naim Muslim Sabir, Mujahid Malik-ul-Mule'),
    (132,'New Oriental Hall (Universal Islamic Society) (Historic, 1926)','1941 Hastings Street Detroit, MI','NULL','NULL','NULL','NULL','1926','1926','NULL','1940','NULL','The purpose of the church shall be for religious and benevolent services.  The group was incorporated on October 12, 1925.  Duse Ali''s name is not listed in the incorporation papers.  Universal Islamic Society sponsored a united Eid al Fitr with both Sunni and Shia at the New Oriental Hall at this Hastings Street address on April 13, 1926.  The Detroit News was on hand to cover the story and mentions that Sheikh Kalil Bazzy led the prayer.','NULL','NULL','NULL','NULL','President: Duse Mohammed Ali; effendi Vice-President: Shah Zain ul Abedin; Incorporators: Joseph Ferris, 1407 Sherman, Detroit, MI; S.Z. Abedian, 1407 Sherman, Detroit, MI; Kallil Zhidy, 1407 Sherman, Detroit, MI; Mohamid Aiddora, 1407 Sherman, Detroit, MI; A.W. Ahmed, 1407 Sherman, Detroit, MI.'),
    (133,'Progressive Arabian Hashemite Society (Hashemite Hall) (Historic)','10401 Dix Avenue Dearborn, MI','NULL','NULL','NULL','NULL','1936','NULL','NULL','1970''s','NULL','"The Progressive Arabian Hashmite Society" incorporated with the state in July of 1936.  The group quickly set about purchasing and renovating the above address and celebrated the grand opening and dedication of the mosque under the name, Progressive Arabian Hashemite Society on May 30, 1937.  The Hashemite Society rented space in this former bank until they were able to purchase the building in 1939.  The building was used primarily as a social club, but also as a mosque and Sunday school on and off until it was eclipsed by the Islamic Center of America which opened in 1963.  The building burned down in the 1970''s.','NULL','NULL','NULL','NULL','Kaid Lahage (Detroit), Aly Harb (Dearborn), Mohamed Forge (Dearborn), and Ollie Samhat (Highland Park)'),
    (134,'Sacred Mosque (Historic)','201 Tuxedo Street Highland Park, MI','NULL','NULL','NULL','NULL','1987','NULL','NULL','1997','NULL','Incorporated in 1987 and disbanded in 1997, this mosque was associated with the Nation of Islam.','NULL','NULL','NULL','NULL','NULL'),
    (135,'Tijani Zawiya','19174 Livernois Avenue Detroit, MI','NULL','NULL','NULL','NULL','1999','1999','NULL','2007','NULL','NULL','NULL','NULL','NULL','NULL','NULL'),
    (136,'Turkish Crescent Association','3048 Salina Dearborn, MI','NULL','NULL','NULL','NULL','1950''s','NULL','NULL','NULL','NULL','This association shows up in Dearborn City Directories from the 1950''s.','NULL','NULL','NULL','NULL','NULL'),
    (137,'United Citizen''s Society/Moslem Mosque of Highland Park (Historic)','97 Victor Avenue Highland Park, MI','NULL','NULL','NULL','NULL','1937','1946','NULL','1965','NULL','The United Syrian Citizen''s Society purchased this building in 1937 for the establishment of a mosque.  In the 1940''s and 50''s the building was used for occasional lectures and other education activities, such as Arabic and Quranic classes.  It is unclear when the group took the name Moslem Mosque of Highland Park, but this name was photographed in 1956 by the Detroit Free Press. The group incorporated in March 1958, as a "Moslem church" with a charter from Islamic Center, Washington D.C.. The incorporation provisions make several points, 1. That the group is to be non-sectarian, 2. That it hopes to buy, rent, or build a "mosque".  Nonetheless, the group''s membership was Shi''a and was closely connected to the Progressive Arabian Hashemite Society in Dearborn.  Incorporating members included Mike Hamzey, Allia Agemy, Hussein Alli Hamood, Mustafa Salem, Mustafa Hayime, Abdul Beryy, Charles Allie, and Mohammed Berry.  All but Mr. Berry lived in Highland Park.  Berry lived on Electric Street in Detroit.  In 1963, Hussein Hamood became the registered agent, and in 1964, Kamal Nasser became the agent.  Shortly after this, the group folded their books into those of the Islamic Center of America (Detroit) in exchange for a position or two on the ICD''s board of directors.  The building was sold and the proceeds given to the ICD.','NULL','NULL','NULL','NULL','NULL'),
    (138,'Universal Consolidation of Islam, Holy Mosque (Historic)','5683 Maybury Grand Detroit, MI','NULL','NULL','African American','NULL','1964','NULL','NULL','1977','NULL','At this address, the home of Imam Sammsan, the Universal Consolidation of Islam, Holy Mosque, was incorporated in 1964.  A number of African American Muslims prayed here in the 1960''s.  The group''s articles of incorporation disassociate them from "Black Muslims", Communists, and other "cults" and assert that Islam is "not prejudiced towards races, colors, language, or national origin".  In addition to Hajj Sammsan, Imam, Gwendoline Sammsan and Anas Hassan are listed as incorporating members.  The group was dissolved in 1977.','NULL','NULL','NULL','NULL','Hajj Sammsan, Imam, Gwendoline Sammsan and Anas Hassan'),
    (139,'NULL','574 E. Lafayette Avenue Detroit, MI','NULL','NULL','NULL','NULL','NULL','NULL','NULL','NULL','NULL','This is where Muslims met during the early years of the Great Depression and tried to scrape together work, meals, and the means to keep themselves going during the lean years.  In 1932, the Free Press ran a series of stories that mentioned Muslims requesting a soup kitchen to feed the 4000 or so men who were without support.  They were barred from eating at other kitchens because the food was regularly seasoned with lard.  One article mentions that the men were from Albania, India, Afghanistan, Arabia, and Turkey.','NULL','NULL','NULL','NULL','NULL');


--
-- Constraints for dumped tables
--

--
-- Constraints for table `connection`
--
ALTER TABLE `connection`
  ADD CONSTRAINT `HAS_CONNECTION_P` FOREIGN KEY (`precedes`) REFERENCES `mosque` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `HAS_CONNECTION_S` FOREIGN KEY (`succedes`) REFERENCES `mosque` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
